version: '3'

networks:
  beam-network:
    driver: bridge

services:

  ## Messaging & Streaming

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - beam-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - beam-network

  ## Storage & DB
  cassandra:
    image: 'cassandra:latest'
    networks:
      - beam-network
  ## BEAM

  maven:
    image: adoptopenjdk/maven-openjdk11
    container_name: maven
    working_dir: /app
    networks:
      - beam-network
    volumes:
      - ./pipeline:/app
      - ./source-data/pedestrian:/source-data/pedestrian
    command: /app/deployment.sh

volumes:
  trino:
    driver: local
  metastore_conf:
    driver: local
  minio-data:
    driver: local
  metabase:
    driver: local
  cli:
    driver: local  